# Generated by Django 5.0.3 on 2024-05-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0003_tipocuota_usuario_direccion_usuario_tipo_de_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='pago',
            new_name='fecha_de_pago',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='solicitud_nueva_rutina',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_pago',
            field=models.CharField(choices=[('E', 'Efectivo'), ('T', 'Transferencia')], max_length=20),
        ),
    ]
