# Generated by Django 5.0.3 on 2024-05-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0004_rename_pago_usuario_fecha_de_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
