# Generated by Django 5.0.3 on 2024-05-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0006_usuario_tipo_de_cuota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoCuota',
            new_name='TipoPlanes',
        ),
    ]
