# Generated by Django 5.0.3 on 2024-05-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0007_rename_tipocuota_tipoplanes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoPlanes',
            new_name='TipoPlan',
        ),
    ]
