# Generated by Django 5.0.3 on 2024-05-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0008_rename_tipoplanes_tipoplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoplan',
            options={'verbose_name': 'Tipo de plan', 'verbose_name_plural': 'Tipos de Planes'},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_de_cuota',
            new_name='tipo_de_plan',
        ),
    ]
