# Generated by Django 5.0.3 on 2024-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0009_alter_tipoplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
