# Generated by Django 5.0.3 on 2024-05-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0010_usuario_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField()),
                ('tipo_de_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magna_app.tipoplan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magna_app.usuario')),
            ],
            options={
                'verbose_name': 'Historial Tipo de Plan Usuario',
                'verbose_name_plural': 'Historiales de Tipos de Planes Usuarios',
            },
        ),
    ]
