# Generated by Django 5.0.3 on 2024-05-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0012_remove_pricehistorys_tipo_de_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistorys',
            name='fecha_cambio',
        ),
    ]
