# Generated by Django 5.0.3 on 2024-05-20 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0013_remove_pricehistorys_fecha_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistorys',
            name='fecha_de_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
