# Generated by Django 5.0.3 on 2024-05-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0014_pricehistorys_fecha_de_pago'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceHistorys',
            new_name='PreciosHistorico',
        ),
        migrations.AlterModelOptions(
            name='precioshistorico',
            options={},
        ),
    ]
