# Generated by Django 5.0.6 on 2024-05-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0015_rename_pricehistorys_precioshistorico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vencimiento',
            field=models.DateField(blank=True, help_text='Si no es especificado será al mes siguiente a la fecha de pago', null=True),
        ),
    ]
