# Generated by Django 5.0.6 on 2024-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0016_alter_usuario_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioshistorico',
            name='usuario',
        ),
        migrations.AddField(
            model_name='precioshistorico',
            name='usuario_nombre',
            field=models.CharField(default='genaro', max_length=50),
            preserve_default=False,
        ),
    ]
