# Generated by Django 5.0.6 on 2024-05-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magna_app', '0018_alter_asistencia_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precioshistorico',
            options={'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos realizados'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='dia',
            field=models.DateField(auto_now=True),
        ),
    ]
